### ISSUE TITLE
iOS 10 : XCode 8 : preferredStatusBarStyle

### ISSUE THREAD

**Issue by hitendradeveloper** [cezarywojcik/CWStatusBarNotification#96] opened 2016-09-17 05:38 UTC
Hi, I have just run my project in XCod8 and give me error as show in the below image.

![Error preferredStatusBarStyle](https://cloud.githubusercontent.com/assets/9197369/18606230/23cab904-7cc7-11e6-8871-2667ae5f34f7.png)

Reason behind the error : 

In iOS 10 **preferredStatusBarStyle** is implemented as property in UIViewController.
-Source Apple:

> @property(nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle NS_AVAILABLE_IOS(7_0) __TVOS_PROHIBITED; // Defaults to UIStatusBarStyleDefault

**Comment by cezarywojcik** [comment] 2016-09-17 12:05
dupe of https://github.com/cezarywojcik/CWStatusBarNotification/issues/95

**Closed by cezarywojcik** 2016-09-17 12:05 UTC
Labels: duplicate
